version: "3.7"
services:
  db:
    image: postgres:15-alpine
    container_name: ${PROJECT}-db-${ENV}
    restart: always
    env_file: .env
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5434:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - tc

  frontend:
    container_name:  ${PROJECT}-frontend-${ENV}
    entrypoint: sh -c "npm ci && npm run dev"
    environment:
      NODE_ENV: ${ENV}
      PORT: 3000
      BACKEND_URL: http://backend:3000
    image: node:20-bullseye
    ports: 
      - "3000:3000"
    volumes: ["./frontend:/app", "/app/node_modules"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
    working_dir: "/app"
    networks:
      - tc
    depends_on:
      - backend
  caddy:
    container_name:  ${PROJECT}-caddy-${ENV}
    profiles: ["caddy"]
    build: ./frontend
    environment:
      NODE_ENV: ${ENV}
      PORT: 3000
      BACKEND_URL: http://backend:3000
      LOG_LEVEL: info
    ports: ["3005:3000"]
    volumes: ["./frontend/Caddyfile:/etc/caddy/Caddyfile"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
    depends_on:
    - backend
    networks:
      - tc
  backend:
    container_name: ${PROJECT}-backend-${ENV}
    build:
      context: ./backend
      dockerfile: Dockerfile.local
    stdin_open: true
    ports: 
    - "3001:3000"
    - 9229:9229 # 9229 is the default node debug port
    volumes: 
      - "./backend:/usr/src/app"
      - "/usr/src/app/node_modules"
    environment:
      NODE_ENV: ${ENV}
      PORT: 3000
      DB_PORT: ${DB_PORT}
      DB_HOST: ${DB_HOST}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      KEYCLOAK_REALM:  ${KEYCLOAK_REALM}
      KEYCLOAK_AUTH_URL: ${KEYCLOAK_AUTH_URL}
      KEYCLOAK_CLIENT: ${KEYCLOAK_CLIENT}
      BCWS_TOKEN: ${BCWS_TOKEN}
      CHEFS_WS_TOKEN: ${CHEFS_WS_TOKEN}
      CHEFS_API: ${CHEFS_API}
      CHEFS_API_KEY: ${CHEFS_API_KEY}
      CHIPS_API: ${CHIPS_API}
      CHIPS_API_KEY: ${CHIPS_API_KEY}
      CHEFS_FORM_ENABLED: ${CHEFS_FORM_ENABLED} 
      CHEFS_FORM_ID: ${CHEFS_FORM_ID}
      CHES_API: ${CHES_API}
      CHES_AUTH_API: ${CHES_AUTH_API}
      CHES_CLIENT_ID: ${CHES_CLIENT_ID}
      CHES_CLIENT_SECRET: ${CHES_CLIENT_SECRET}
      DB_PASSWORD: ${DB_PASSWORD}
      MODE: ${MODE}
      END_RECOMMITMENT_SCHEDULE: ${END_RECOMMITMENT_SCHEDULE}
      TEST_EMAIL: ${TEST_EMAIL}
      CHOKIDAR_USEPOLLING: true
      ALLOW_EMPTY_PASSWORD: "yes"
      ENV: ${ENV}
    networks:
      - tc
  keycloak:
    container_name: ${PROJECT}-keycloak-${ENV}
    build:
      context: ./keycloak
    command:
      - start-dev
      - --import-realm
      - --hostname-strict=false
      - --hostname-strict-https=false
    platform: linux/arm64/v8
    volumes:
      - keycloak:/opt/keycloak/data
      - ./keycloak/export:/opt/keycloak/data/import
      - ./keycloak/export:/export
    env_file: .env
    environment:
      KEYCLOAK_IMPORT: /opt/keycloak/data/import
      DB_VENDOR: ${DB_TYPE}
      DB_ADDR: db
      DB_URL: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${DB_NAME}
      DB_USERNAME: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      CHEFS_WS_TOKEN: ${CHEFS_WS_TOKEN}
      CHEFS_API: ${CHEFS_API}
      CHEFS_API_KEY: ${CHEFS_API_KEY}
      CHEFS_FORM_ID: ${CHEFS_FORM_ID}
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_PASSWORD}
      HEALTH_ENABLED: "true"
      HTTP_ENABLED: "true"
      METRICS_ENABLED: "true"
      TEST_EMAIL: ${TEST_EMAIL}
    depends_on:
      - db
    ports:
      - "8080:8080"
      - "8787:8787" # debug port
    networks:
      - tc
volumes:
  pg_data: {}
  keycloak: {}
networks:
  tc:
    driver: bridge
