version: "3.7"
services:
  db:
    image: postgres:15-alpine
    container_name: ${PROJECT}-db
    restart: always
    env_file: .env
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - tc

  frontend:
    image: ${PROJECT}-frontend:${GIT_LOCAL_BRANCH}
    container_name: ${PROJECT}-frontend
    command: "npm run start"
    build:
      context: "./frontend"
      target: dev
    restart: always
    stdin_open: true
    environment:
      REACT_APP_SSO_REDIRECT_URI: ${REACT_APP_SSO_REDIRECT_URI}
      REACT_APP_SSO_AUTH_SERVER_URL: ${REACT_APP_SSO_AUTH_SERVER_URL}
      REACT_APP_SSO_REALM: ${REACT_APP_SSO_REALM}
      REACT_APP_SSO_CLIENT_ID: ${REACT_APP_SSO_CLIENT_ID}
      REACT_APP_URL: ${REACT_APP_URL}
      REACT_APP_PORT: ${REACT_APP_PORT}
      CHOKIDAR_USEPOLLING: "true"
      WATCHPACK_POLLING: "true"
      # uncomment if hot reload fails (windows only?)
      # WDS_SOCKET_HOST: "127.0.0.1"
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
      - ./frontend:/app
    depends_on:
      - backend
      - keycloak
    networks:
      - tc
  backend:
    container_name: ${PROJECT}-backend
    image: ${PROJECT}-backend:${GIT_LOCAL_BRANCH}
    build:
      context: "./backend"
      target: dev
    restart: always
    stdin_open: true
    command: "npm run start:dev"
    environment:
      PORT: ${API_PORT}
      DB_PORT: ${DB_PORT}
      DB_HOST: ${DB_HOST}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      CHOKIDAR_USEPOLLING: "true"
      ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "8081:8081"
    volumes:
      - /usr/src/app/node_modules
      - ./backend:/usr/src/app
    depends_on:
      - db
    networks:
      - tc

  nginx:
    image: ${PROJECT}-nginx:${GIT_LOCAL_BRANCH}
    container_name: ${PROJECT}-nginx
    build:
      context: "./nginx"
    ports:
      - "3050:80"
    depends_on:
      - backend
      - frontend
    networks:
      - tc

  keycloak:
    container_name: keycloak
    build:
      context: ./keycloak
    command:
      - start-dev
      - --import-realm
      - --hostname-strict=false
      - --hostname-strict-https=false
      # - --hostname=localhost
      # - --proxy=edge
      # - --hostname-url=http://localhost:3050
      # - --hostname-strict-backchannel=true
    platform: linux/arm64/v8
    volumes:
      - keycloak:/opt/keycloak/data
      - ./keycloak/default.json:/opt/keycloak/data/import/default.json
    environment:
      KEYCLOAK_IMPORT: /opt/keycloak/data/import/default.json
      DB_VENDOR: ${DB_TYPE}
      DB_ADDR: db
      DB_URL: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${DB_NAME}
      DB_USERNAME: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_PASSWORD}
      HEALTH_ENABLED: "true"
      HTTP_ENABLED: "true"
      METRICS_ENABLED: "true"
    depends_on:
      - db
    ports:
      - "8080:8080"
      - "8787:8787" # debug port
    networks:
      - tc
volumes:
  pg_data: {}
  keycloak: {}
networks:
  tc:
    driver: bridge
