kind: Template
apiVersion: template.openshift.io/v1
labels:
  app: ${APP_NAME}
parameters:
  - name: APP_NAME
    description: App name that OpenShift objects will be prefixed with
    required: true
  - name: IMAGE_NAMESPACE
    description: Namespace from which to pull the image
    required: true
  - name: IMAGE_TAG
    description: Image tag from image stream
    value: latest
    required: true
  - name: SERVER_PORT
    description: Port the server will be exposed on
    value: '8080'
    required: true
  - name: CONFIG_VERSION
    description: The github repository version of Config (Commit SHA)
    value: default
  - name: REPLICAS
    description: The number of replicas of deployments
    value: '3'
objects:
  - apiVersion: v1
    kind: Route
    metadata:
      name: ${APP_NAME}-server
      annotations:
        haproxy.router.openshift.io/timeout: 90s
        haproxy.router.openshift.io/disable_cookies: true
    spec:
      host: ''
      port:
        targetPort: web
      tls:
        insecureEdgeTerminationPolicy: Redirect
        termination: edge
      to:
        kind: Service
        name: ${APP_NAME}-server
        weight: 100
      wildcardPolicy: None
  - kind: DeploymentConfig
    apiVersion: v1
    metadata:
      name: ${APP_NAME}-server
    spec:
      strategy:
        type: Rolling
        activeDeadlineSeconds: 21600
      triggers:
        - imageChangeParams:
            automatic: true
            containerNames:
              - ${APP_NAME}-server
            from:
              kind: ImageStreamTag
              name: ${APP_NAME}-server:${IMAGE_TAG}
              namespace: ${IMAGE_NAMESPACE}
          type: ImageChange
        - type: ConfigChange
      replicas: '${{REPLICAS}}'
      selector:
        name: ${APP_NAME}-server
      template:
        metadata:
          name: ${APP_NAME}-server
          labels:
            name: ${APP_NAME}-server
        spec:
          containers:
            - name: ${APP_NAME}-server
              env:
                - name: ENV
                  value: dev
                - name: CONFIG_VERSION
                  value: ${CONFIG_VERSION}
                - name: POSTGRES_HOST
                  value: ${APP_NAME}-patroni-creds
                - name: POSTGRES_DB
                  valueFrom:
                    secretKeyRef:
                      key: app-db-name
                      name: ${APP_NAME}-patroni-creds
                - name: POSTGRES_USER
                  valueFrom:
                    secretKeyRef:
                      key: app-db-username
                      name: ${APP_NAME}-patroni-creds
                - name: POSTGRES_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      key: app-db-password
                      name: ${APP_NAME}-patroni-creds
                - name: KEYCLOAK_REALM
                  valueFrom:
                    secretKeyRef:
                      key: realm
                      name: ${APP_NAME}-keycloak
                - name: KEYCLOAK_AUTH_URL
                  valueFrom:
                    secretKeyRef:
                      key: auth-url
                      name: ${APP_NAME}-keycloak
                - name: KEYCLOAK_CLIENT
                  valueFrom:
                    secretKeyRef:
                      key: client
                      name: ${APP_NAME}-keycloak
              image: image-registry.openshift-image-registry.svc:5000/${IMAGE_NAMESPACE}/${APP_NAME}-server:${IMAGE_TAG}
              ports:
                - containerPort: '${{SERVER_PORT}}'
                  protocol: TCP
              resources:
                limits:
                  cpu: '100m'
                  memory: 256Mi
                requests:
                  cpu: 50m
                  memory: 128Mi
              terminationMessagePath: /dev/termination-log
              terminationMessagePolicy: File
              imagePullPolicy: Always
          restartPolicy: Always
          dnsPolicy: ClusterFirst
  - kind: Service
    apiVersion: v1
    metadata:
      name: ${APP_NAME}-server
    spec:
      ports:
        - name: web
          protocol: TCP
          port: ${{SERVER_PORT}}
          targetPort: ${{SERVER_PORT}}
      selector:
        name: ${APP_NAME}-server
      type: ClusterIP
      sessionAffinity: None
