kind: Template
apiVersion: template.openshift.io/v1
labels:
  app: ${APP_NAME}
parameters:
  - name: APP_NAME
    description: App name that OpenShift objects will be prefixed with
    required: true
  - name: ENV
    description: Environment name
    value: dev
    required: true
  - name: IMAGE_NAMESPACE
    description: Namespace from which to pull the image
    required: true
  - name: IMAGE_TAG
    description: Image tag from image stream
    value: latest
    required: true
  - name: SERVER_PORT
    description: Port the server will be exposed on
    value: '3000'
    required: true
  - name: CONFIG_VERSION
    description: The github repository version of Config (Commit SHA)
    value: default
  - name: REPLICAS
    description: The number of replicas of deployments
    value: '3'
objects:
  - apiVersion: v1
    kind: Route
    metadata:
      name: ${APP_NAME}-server
      annotations:
        haproxy.router.openshift.io/timeout: 90s
        haproxy.router.openshift.io/disable_cookies: true
    spec:
      host: ''
      port:
        targetPort: web
      tls:
        insecureEdgeTerminationPolicy: Redirect
        termination: edge
      to:
        kind: Service
        name: ${APP_NAME}-server
        weight: 100
      wildcardPolicy: None
  - kind: DeploymentConfig
    apiVersion: v1
    metadata:
      name: ${APP_NAME}-server
    spec:
      strategy:
        type: Rolling
        activeDeadlineSeconds: 21600
      triggers:
        - imageChangeParams:
            automatic: true
            containerNames:
              - ${APP_NAME}-server
            from:
              kind: ImageStreamTag
              name: ${APP_NAME}-server:${IMAGE_TAG}
              namespace: ${IMAGE_NAMESPACE}
          type: ImageChange
        - type: ConfigChange
      replicas: '${{REPLICAS}}'
      selector:
        name: ${APP_NAME}-server
      template:
        metadata:
          name: ${APP_NAME}-server
          labels:
            name: ${APP_NAME}-server
        spec:
          containers:
            - name: ${APP_NAME}-server
              env:
                - name: ENV
                  valueFrom:
                    configMapKeyRef:
                      key: app-env
                      name: ${APP_NAME}-server-config
                - name: NODE_ENV
                  value: production
                - name: PORT
                  value: '3000'
                - name: CONFIG_VERSION
                  value: ${CONFIG_VERSION}
                - name: CHES_API
                  value: ${CHES_API}
                - name: CHES_AUTH_API
                  value: {CHES_AUTH_API}
                - name: DB_HOST
                  value: ${APP_NAME}-patroni
                - name: DB_NAME
                  valueFrom:
                    secretKeyRef:
                      key: app-db-name
                      name: ${APP_NAME}-patroni-creds
                - name: DB_USER
                  valueFrom:
                    secretKeyRef:
                      key: app-db-username
                      name: ${APP_NAME}-patroni-creds
                - name: DB_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      key: app-db-password
                      name: ${APP_NAME}-patroni-creds
                - name: KEYCLOAK_REALM
                  valueFrom:
                    secretKeyRef:
                      key: realm
                      name: ${APP_NAME}-keycloak
                - name: KEYCLOAK_AUTH_URL
                  valueFrom:
                    secretKeyRef:
                      key: auth-url
                      name: ${APP_NAME}-keycloak
                - name: KEYCLOAK_CLIENT
                  valueFrom:
                    secretKeyRef:
                      key: client
                      name: ${APP_NAME}-keycloak
                - name: CHES_CLIENT_ID
                  valueFrom:
                    secretKeyRef:
                      key: ches_client_id
                      name: ${APP_NAME}-ches
                - name: CHES_CLIENT_SECRET
                  valueFrom:
                    secretKeyRef:
                      key: ches_client-secret
                      name: ${APP_NAME}-ches
                - name: MODE
                  valueFrom:
                    secretKeyRef:
                      key: mode
                      name: ${APP_NAME}-ches
                - name: CHEFS_API
                  valueFrom:
                    secretKeyRef:
                      key: base_url
                      name: ${APP_NAME}-chefs
                - name: CHEFS_API_KEY
                  valueFrom:
                    secretKeyRef:
                      key: api_key
                      name: ${APP_NAME}-chefs
                - name: CHEFS_WS_TOKEN
                  valueFrom:
                    secretKeyRef:
                      key: token
                      name: ${APP_NAME}-chefs
                - name: CHEFS_FORM_ID
                  valueFrom:
                    secretKeyRef:
                      key: form_id
                      name: ${APP_NAME}-chefs
                - name: CHEFS_FORM_ENABLED
                  valueFrom:
                    secretKeyRef:
                      key: enabled
                      name: ${APP_NAME}-chefs
                - name: CHIPS_API
                  valueFrom:
                    secretKeyRef:
                      key: base_url
                      name: ${APP_NAME}-chips
                - name: CHIPS_API_KEY
                  valueFrom:
                    secretKeyRef:
                      key: api_key
                      name: ${APP_NAME}-chips
                - name: BCWS_TOKEN
                  valueFrom:
                    secretKeyRef:
                      key: bcws_token
                      name: ${APP_NAME}-bcws
              image: image-registry.openshift-image-registry.svc:5000/${IMAGE_NAMESPACE}/${APP_NAME}-server:${IMAGE_TAG}
              ports:
                - containerPort: '${{SERVER_PORT}}'
                  protocol: TCP
              resources:
                limits:
                  cpu: 75m
                  memory: 256Mi
                requests:
                  cpu: 35m
                  memory: 128Mi
              terminationMessagePath: /dev/termination-log
              terminationMessagePolicy: File
              imagePullPolicy: Always
          restartPolicy: Always
          dnsPolicy: ClusterFirst
  - kind: Service
    apiVersion: v1
    metadata:
      name: ${APP_NAME}-server
    spec:
      ports:
        - name: web
          protocol: TCP
          port: ${{SERVER_PORT}}
          targetPort: ${{SERVER_PORT}}
      selector:
        name: ${APP_NAME}-server
      type: ClusterIP
      sessionAffinity: None
