kind: Template
apiVersion: template.openshift.io/v1
labels:
  app: ${APP_NAME}
parameters:
  - name: APP_NAME
    description: App name that OpenShift objects will be prefixed with
    required: true
  - name: KEYCLOAK_REALM
    description: Keycloak realm identifier
    value: standard
    required: true
  - name: KEYCLOAK_AUTH_SERVER
    description: Placeholder for URL used to request authentication actions with Keycloak
    required: true
  - name: KEYCLOAK_CLIENT
    description: Placeholder for client id for Keycloak
    value: 'talent-cloud-5163'
    required: true
  - name: APP_ENV
    description: Environment for the application
    required: true
    value: dev
  - name: BCWS_TOKEN
    description: Token for BCWS integration
    generate: expression
    from: '[a-zA-Z0-9]{32}'
    required: true
objects:
  - kind: Secret
    apiVersion: v1
    metadata:
      name: ${APP_NAME}-keycloak
    stringData:
      realm: ${KEYCLOAK_REALM}
      auth-url: ${KEYCLOAK_AUTH_SERVER}
      client: ${KEYCLOAK_CLIENT}
  - kind: Secret
    apiVersion: v1
    metadata:
      name: ${APP_NAME}-chefs
    stringData:
      base_url: ${CHEFS_API}
      api_key: ${CHEFS_API_KEY}
      token: ${CHEFS_WS_TOKEN}
      form_id: ${CHEFS_FORM_ID}
      enabled: ${CHEFS_FORM_ENABLED}
  - kind: Secret
    apiVersion: v1
    metadata:
      name: ${APP_NAME}-chips
    stringData:
      base_url: ${CHIPS_API}
      api_key: ${CHIPS_API_KEY}
  - kind: Secret
    apiVersion: v1
    metadata:
      name: ${APP_NAME}-bcws
    stringData:
      bcws_token: ${BCWS_TOKEN}
  - kind: ConfigMap
    apiVersion: v1
    metadata:
      name: ${APP_NAME}-server-config
    data:
      app-env: ${APP_ENV}
  - kind: Secret
    apiVersion: v1
    metadata:
      name: ${APP_NAME}-ches
    stringData:
      ches_client_id: ${CHES_CLIENT_ID}  
      ches_client_secret: ${CHES_CLIENT_SECRET}
      ches_api: ${CHES_API}
      ches_auth_api: ${CHES_AUTH_API}
  - kind: Secret
    apiVersion: v1
    metadata:
      name: ${APP_NAME}-recommitment
    stringData:
      start_date: ${START_DATE}
      end_date: ${END_DATE}
      test_email: ${TEST_EMAIL}
      schedule: ${SCHEDULE}

                
                
                
                
                  