name: Lint

on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - edited
      - reopened
      - synchronize
      - ready_for_review

jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3
        name: checkout

      - uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Install Frontend Dependencies
        run: cd frontend && npm ci

      - name: Lint Check Frontend
        run: cd frontend && npm run lint

      - name: Install Backend Dependencies
        run: cd backend && npm ci

      - name: Lint Check Backend
        run: cd backend && npm run lint
