name: Run Migrations (Test)

on:
  workflow_dispatch:  

env:
  CLUSTER: https://api.gold.devops.gov.bc.ca:6443
  AUTH_TOKEN: ${{ secrets.OC_AUTH_TOKEN }}
  TOOLS_TOKEN: ${{ secrets.OC_TOOLS_TOKEN }}
  PROJECT: tcloud

jobs:
  run_migrations:
    name: Run Migrations (Test)
    environment: test
    runs-on: ubuntu-latest
    timeout-minutes: 20
    env:
      OS_NAMESPACE_SUFFIX: test
      AUTH_TOKEN: ${{ secrets.OC_AUTH_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup ENV file
        run: cp .env.example .env
      - name: Cache OpenShift CLI
        id: cache-oc
        uses: actions/cache@v2
        with:
          path: /usr/local/bin/oc
          key: ${{ runner.os }}-oc
      - name: Cache OpenShift CLI
        id: cache-oc
        uses: actions/cache@v4
        with:
          path: /usr/local/bin/oc
          key: ${{ runner.os }}-oc
      - name: Install OpenShift CLI
        if: steps.cache-oc.outputs.cache-hit != 'true'
        run: |
          wget https://mirror.openshift.com/pub/openshift-v4/clients/oc/latest/linux/oc.tar.gz
          tar -xvf oc.tar.gz
          sudo mv oc /usr/local/bin/

      - name: Run migrations
        run: |
          cd "$GITHUB_WORKSPACE"
          oc login --token="${{ env.AUTH_TOKEN }}" --server="$CLUSTER"
          export OS_NAMESPACE_SUFFIX=${{ env.OS_NAMESPACE_SUFFIX }}
          make migration-run-oc
      